/**
 * Codegen：端点契约表 → typed client SDK。
 *
 * 跑法：npx tsx packages/client/script/generate.ts（在 ts/ 目录下）
 * 产物：packages/client/src/generated/{endpoints.ts, events.ts}
 *
 * 幂等：同契约必同产物（无时间戳/随机序），重跑 diff 为空；
 * 手改生成物无效——改契约（packages/protocol）后重跑本脚本。
 */
import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import { ENDPOINTS, type EndpointDef } from "../../protocol/src/endpoints";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const GENERATED_DIR = path.resolve(__dirname, "../src/generated");
/** generated/ 文件位于 packages/client/src/generated/，protocol 在 packages/protocol/ */
const PROTOCOL_IMPORT = "../../../protocol/src";

const HEADER = (source: string) => `/* AUTO-GENERATED by packages/client/script/generate.ts — do not edit.
 * 契约源：packages/protocol/src/${source}
 * 重新生成：npx tsx packages/client/script/generate.ts
 */
`;

/* ------------------------------------------------------------------ */
/*  helpers                                                            */
/* ------------------------------------------------------------------ */

const BUILTIN_TYPES = new Set(["string", "unknown", "void"]);

/** 收集生成文件需要 import 的协议类型名（排序保证确定序） */
function collectTypeImports(): string[] {
  const names = new Set<string>();
  for (const e of ENDPOINTS) {
    for (const t of [e.query, e.request, e.response]) {
      if (!t) continue;
      const base = t.replace(/\[\]$/, "");
      if (!BUILTIN_TYPES.has(base)) names.add(base);
    }
  }
  return [...names].sort();
}

function fnParams(e: EndpointDef): string {
  const params: string[] = ["client: ClientAdapter"];
  for (const p of e.pathParams ?? []) params.push(`${p}: string`);
  if (e.query) params.push(`query${e.queryRequired ? "" : "?"}: ${e.query}`);
  if (e.request) params.push(`body${e.requestBodyOptional ? "?" : ""}: ${e.request}`);
  return params.join(", ");
}

function fnBody(e: EndpointDef): string {
  // URL 表达式（生成代码中的模板字面量内容）：
  //   :param → ${encodeURIComponent(param)}；query → ${buildQuery(query)}
  // 注：用字符串拼接而非模板串，保证 ${...} 作为字面文本进入生成物
  let urlExpr = e.path.replace(
    /:([A-Za-z][A-Za-z0-9]*)/g,
    (_m, p: string) => "${encodeURIComponent(" + p + ")}"
  );
  if (e.query) urlExpr += "${buildQuery(query)}";

  const hasBody = e.request !== undefined;
  let init: string;
  if (hasBody) {
    const stringify = "JSON.stringify(body" + (e.requestBodyOptional ? " ?? {}" : "") + ")";
    init =
      ', {\n    method: "' +
      e.method +
      '",\n    headers: { "Content-Type": "application/json" },\n    body: ' +
      stringify +
      ",\n  }";
  } else if (e.method === "GET") {
    init = "";
  } else {
    init = ', { method: "' + e.method + '" }';
  }
  return (
    "  return client.fetch(`" + urlExpr + "`" + init + ") as Promise<" + e.response + ">;"
  );
}

function fnDoc(e: EndpointDef): string {
  const lines = [`${e.method} ${e.path}`];
  if (e.summary) lines.push(e.summary);
  if (e.sse) lines.push("@sse 响应为 text/event-stream——普通 fetch 将挂到流结束；事件订阅请用 subscribeEvents。");
  return lines.map((l) => ` * ${l}`).join("\n");
}

function fn(e: EndpointDef): string {
  return `/**
${fnDoc(e)}
 */
export function ${e.name}(${fnParams(e)}): Promise<${e.response}> {
${fnBody(e)}
}`;
}

/* ------------------------------------------------------------------ */
/*  generated/endpoints.ts                                             */
/* ------------------------------------------------------------------ */

function genEndpointsFile(): string {
  const imports = collectTypeImports();
  const needBuildQuery = ENDPOINTS.some((e) => e.query !== undefined);
  const buildQueryHelper = needBuildQuery
    ? `
/** 拼 query string（跳过 undefined/null 值） */
function buildQuery(query?: object): string {
  if (!query) return "";
  const parts: string[] = [];
  for (const [key, value] of Object.entries(query)) {
    if (value === undefined || value === null) continue;
    parts.push(encodeURIComponent(key) + "=" + encodeURIComponent(String(value)));
  }
  return parts.length ? "?" + parts.join("&") : "";
}
`
    : "";
  const fns = ENDPOINTS.map(fn).join("\n\n");
  return (
    HEADER("endpoints.ts") +
    `
import type { ClientAdapter } from "../adapter";
${imports.length ? `import type { ${imports.join(", ")} } from "${PROTOCOL_IMPORT}";` : ""}

export const SDK_GENERATED_ENDPOINT_COUNT = ${ENDPOINTS.length};
${buildQueryHelper}
${fns}
`
  );
}

/* ------------------------------------------------------------------ */
/*  generated/events.ts（SSE 订阅，逻辑对齐 PROTOCOL.md §事件流）        */
/* ------------------------------------------------------------------ */

function genEventsFile(): string {
  return (
    HEADER("events.ts") +
    `
import type { DomainEvent } from "${PROTOCOL_IMPORT}";

/** 最小 EventSource 结构接口——不依赖 DOM lib；浏览器与较新 Node 原生提供全局实现 */
export interface EventSourceLike {
  onmessage: ((ev: { data: string }) => void) | null;
  onerror: ((ev: unknown) => void) | null;
  close(): void;
}

export type EventSourceCtor = new (url: string) => EventSourceLike;

export interface SubscribeOptions {
  /** 只接收该项目的事件（服务端过滤键） */
  projectId?: string;
  /** 断线重连续传游标（浏览器 EventSource 自动带 Last-Event-ID，此参用于首连定制） */
  lastEventId?: number;
  /** 注入 EventSource 实现（测试 / 无全局 EventSource 的运行时） */
  eventSourceCtor?: EventSourceCtor;
}

/**
 * 订阅统一事件流（GET /api/events，SSE）。
 *
 * - baseUrl：API 根前缀（同源 web 传 ""；跨端传如 "http://host:3001"）
 * - 断线重连由 EventSource 自动进行并携带 Last-Event-ID，服务端按 seq 补发，不丢事件
 * - 返回退订函数
 */
export function subscribeEvents(
  baseUrl: string,
  onEvent: (event: DomainEvent) => void,
  opts: SubscribeOptions = {}
): () => void {
  const Ctor =
    opts.eventSourceCtor ??
    (globalThis as { EventSource?: EventSourceCtor }).EventSource;
  if (!Ctor) {
    console.warn("[pf-client] EventSource unavailable in this runtime; subscribeEvents is a no-op");
    return () => {};
  }
  const query: string[] = [];
  if (opts.projectId !== undefined) {
    query.push("projectId=" + encodeURIComponent(opts.projectId));
  }
  if (opts.lastEventId !== undefined) {
    query.push("lastEventId=" + encodeURIComponent(String(opts.lastEventId)));
  }
  const qs = query.length ? "?" + query.join("&") : "";
  const es = new Ctor(baseUrl + "/api/events" + qs);
  es.onmessage = (ev) => {
    try {
      onEvent(JSON.parse(ev.data) as DomainEvent);
    } catch {
      /* ignore malformed frame */
    }
  };
  es.onerror = () => {
    /* EventSource 自动重连并携带 Last-Event-ID；这里无需额外处理 */
  };
  return () => es.close();
}
`
  );
}

/* ------------------------------------------------------------------ */
/*  main                                                               */
/* ------------------------------------------------------------------ */

function main(): void {
  fs.mkdirSync(GENERATED_DIR, { recursive: true });
  const endpointsFile = path.join(GENERATED_DIR, "endpoints.ts");
  const eventsFile = path.join(GENERATED_DIR, "events.ts");
  fs.writeFileSync(endpointsFile, genEndpointsFile(), "utf8");
  fs.writeFileSync(eventsFile, genEventsFile(), "utf8");

  const sse = ENDPOINTS.filter((e) => e.sse).length;
  console.log(
    `[codegen] ${ENDPOINTS.length} endpoints (${sse} sse) -> ${path.relative(process.cwd(), endpointsFile)}`
  );
  console.log(`[codegen] subscribeEvents -> ${path.relative(process.cwd(), eventsFile)}`);
}

main();
