import { describe, it, expect } from "vitest";
import * as Effect from "effect/Effect";
import { writingCapability } from "@capabilities/research/writing";
import { DeterministicProvider } from "@runtime/provider-deterministic";

describe("Writing Capability - Not Stub", () => {
  it("draft must call Provider (LLM), not return template string", async () => {
    const provider = new DeterministicProvider({
      name: "writing-test",
      responses: [
        {
          content:
            "Real LLM-generated introduction about transformer architectures and their impact on natural language processing.",
          stopReason: "stop",
        },
        {
          content: "8.5",
          stopReason: "stop",
        },
      ],
    });

    const result = (await Effect.runPromise(
      writingCapability.execute({
        topic: "Transformers in NLP",
        provider,
      })
    )) as unknown as {
      outline: Array<{ section: string; content: string }>;
      draft: string;
      review: { score: number; feedback: string };
    };

    // MUST call Provider at least once - proof it's not hardcoded
    expect(provider.getCallCount()).toBeGreaterThan(0);

    // Must NOT return template string
    expect(result.draft).not.toContain("Full draft of the document with");

    // Must contain LLM-generated content
    expect(result.draft).toContain("Real LLM-generated");
  });

  it("draft skill alone must call Provider and return LLM content", async () => {
    const provider = new DeterministicProvider({
      name: "draft-skill-test",
      responses: [
        {
          content:
            "This is a professionally written section about machine learning fundamentals, generated by an LLM.",
          stopReason: "stop",
        },
      ],
    });

    const draftSkill = writingCapability.skills[1];
    const result = (await Effect.runPromise(
      draftSkill.execute({
        outline: [
          { section: "Introduction" },
          { section: "Methods" },
        ],
        provider,
      })
    )) as unknown as { draft: string };

    // MUST call Provider
    expect(provider.getCallCount()).toBeGreaterThan(0);

    // Must NOT be template
    expect(result.draft).not.toContain("Full draft of the document with");
    expect(result.draft).toContain("professionally written");
  });

  it("review skill must call Provider, not return hardcoded score", async () => {
    const provider = new DeterministicProvider({
      name: "review-test",
      responses: [
        {
          content:
            "Score: 9.2\nFeedback: Excellent structure and argumentation. Minor suggestion to expand the methodology section.",
          stopReason: "stop",
        },
      ],
    });

    const reviewSkill = writingCapability.skills[2];
    const result = (await Effect.runPromise(
      reviewSkill.execute({
        draft: "This is a test draft content.",
        provider,
      })
    )) as unknown as {
      review: { score: number; feedback: string };
    };

    // MUST call Provider
    expect(provider.getCallCount()).toBeGreaterThan(0);

    // Must NOT return hardcoded 0.85
    expect(result.review.score).not.toBe(0.85);
    // Must use Provider-generated score
    expect(result.review.score).toBe(9.2);
  });

  it("has correct skill structure", () => {
    expect(writingCapability.skills).toHaveLength(3);
    expect(writingCapability.skills[0].name).toBe("writing_outline");
    expect(writingCapability.skills[1].name).toBe("writing_draft");
    expect(writingCapability.skills[2].name).toBe("writing_review");
  });
});
